# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 04:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 5, 1, 4, 58, 22, 951121)),
        ),
    ]
