# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0003_auto_20160501_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name=datetime.datetime(2016, 5, 2, 0, 11, 4, 746034)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
